# These are supported funding model platforms


custom: # Replace with up to 4 custom sponsorship URLs e.g., [<a href="https://betfury.io/?r=5fa3946347f4280d8c4a6a90" target="_blank"><img src="https://betfury.io/pictures/materials/gif/bf_320x50.gif" alt="betfury.io" /></a>, 'link2']
